ci(test)

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -15,3 +15,38 @@ jobs:
             - uses: actions/checkout@v3
             - name: Build
               run: cargo build --verbose --release
+
+    test_run:
+        runs-on: ubuntu-latest
+
+        steps:
+            - uses: actions/checkout@v3
+            - name: Build
+              run: cargo build --release
+
+            - name: create test dir
+              run: mkdir testdir
+
+            - name: copy binary
+              run: |
+                  cp target/release/rust testdir
+                  cd testdir
+
+            - name: run binary
+              run: |
+                  ./cmake-init --name=test
+                  if [ "$?" -eq 0 ]; then
+                      echo "Test passed"
+                      exit 0
+                  else
+                      echo "Test failed"
+                      exit 1
+                  fi
+
+                  if [[ -f "src/main.c" ]] || [[ -f "CMakeLists.txt" ]]; then
+                      echo "Test passed"
+                      exit 0
+                  else
+                      echo "Test failed"
+                      exit 1
+                  fi
